name: Question
description: Ask a question about using Denev
title: "[Question] "
labels: ["question"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Which area?
      options:
        - CLI usage
        - Installation / update
        - Website / documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Provide as much context as possible (OS, CLI version, command you're trying to use, etc.)
    validations:
      required: true
